# Setup Ubooquity
- name: ubooq container
  docker_container:
    name: "ubooq"
    image: "linuxserver/ubooquity:latest"
    state: "started"
    restart_policy: "always"
    volumes:
    - "{{ deluge_config }}:/config"
    - "{{host_media_downloaded}}/torrents:/downloads"
    ports:
    - "{{ ubooq_port }}:{{ ubooq_port }}"
    env:
      TZ: "{{ TZ_TimeZone }}"
      PUID: "{{ user_id }}"
      PGID: "{{ group_id }}"
      MAXMEM: '{{ max_mem }}'
    log_driver: 'syslog'
    log_opt:
      tag: "ubooq"
