# This playbook will deploy the whole Plex + Usenet Automation Setup inside docker containers. Remove any roles you don't want.

- name: Apply system configuration
  hosts: "{{ target }}"
  remote_user: "{{ user }}"
  become: true
  vars_prompt:
    - name: run_common
      prompt: "Run System Tasks(Y/N)?"
      default: "N"
      private: no

  roles:
    - { role: centos_setup, when: ansible_distribution == "CentOS" and (run_common == "Y" or run_common == "y"), tags: [ 'common' ] }
    - { role: ubuntu_setup, when: ansible_distribution == 'Ubuntu' and (run_common == "Y" or run_common == "y"), tags: [ 'common' ] }

- name: Spin up docker containers for each application in the stack
  hosts: dockbox
  remote_user: hubcaps
  become: true
  become_user: "{{ docker_user }}"
  vars_prompt:
    - name: run_mtn
      prompt: "Install MTN(Y/N)?"
      default: "N"
      private: no
    - name: run_plex
      prompt: "Install Plex(Y/N)?"
      default: "N"
      private: no
    - name: run_sab
      prompt: "Install Sab(Y/N)?"
      default: "N"
      private: no
    - name: run_radarr
      prompt: "Install Radarr(Y/N)?"
      default: "N"
      private: no
    - name: run_sonarr
      prompt: "Install Sonarr(Y/N)?"
      default: "N"
      private: no
    - name: run_hydra
      prompt: "Install Hydra(Y/N)?"
      default: "N"
      private: no
    - name: run_mylar
      prompt: "Install Mylar(Y/N)?"
      default: "N"
      private: no
    - name: run_lazyl
      prompt: "Install Lazy Librarian(Y/N)?"
      default: "N"
      private: no
    - name: run_ubooquity
      prompt: "Install Ubooquity(Y/N)?"
      default: "N"
      private: no

  roles:
    - { role: mtn, when: run_mtn == "Y" or run_mtn == "y", tags: [ 'mtn' ] }
    - { role: plex, when: run_plex == "Y" or run_plex == "y", tags: [ 'plex' ] }
    - { role: sab, when: run_sab == "Y" or run_sab == "y", tags: [ 'sab' ] }
    - { role: radarr, when: run_radarr == "Y" or run_radarr == "y", tags: [ 'radarr' ] }
    - { role: sonarr, when: run_sonarr == "Y" or run_sonarr == "y", tags: [ 'sonarr'] }
    - { role: hydra, when: run_hydra == "Y" or run_hydra == "y", tags: [ 'hydra' ] }
    - { role: mylar, when: run_mylar == "Y" or run_mylar == "y", tags: [ 'mylar' ] }
    - { role: lazyl, when: run_lazyl == "Y" or run_lazyl == "y", tags: [ 'lazyl' ] }
    - { role: ubooquity, when: run_ubooquity == "Y" or run_ubooquity == "y", tags: [ 'ubooquity' ] }
