# This play book handles the downloading of necessary packages and applies firewall opening on the server.

- name: Install necessary packages
  package: name={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python
    - python-pip

- name: Install needed python packages for Ansible to do it's job.
  pip: name={{item}}
  with_items:
    - python-apt
    - docker-py

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install Docker Main
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Start and Enable the docker service
  service:
    name: docker
    state: started
    enabled: yes

# Open up ports for all those dope applications.

- name: Open up the ports
  ufw:
    state: enabled
    policy: allow
    port: "{{ item.portname }}"
  with_items:
    - { portname: "{{ mtn_port }}"}
    - { portname: "{{ plex_port }}"}
    - { portname: "{{ sab_port }}"}
    - { portname: "{{ radarr_port }}"}
    - { portname: "{{ sonarr_port }}"}
    - { portname: "{{ hydra_port }}"}
    - { portname: "{{ mylar_port }}"}
    - { portname: "{{ lazyl_port }}"}
    - { portname: "{{ gazee_port }}"}
    - { portname: "{{ gazee_admin_port }}"}

