- name: 'Start the radarr docker container'
  docker_container:
    image: "linuxserver/radarr:latest"
    name: "radarr"
    env:
      PUID: '{{ user_id }}'
      PGID: '{{ group_id }}'
      TZ: '{{ TZ_TimeZone }}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ radarr_directory }}:/config'
      - '{{ host_media_downloaded }}:/downloads'
      - '{{ host_media_movies_path }}:/movies'
    ports: '{{ radarr_port }}:{{ radarr_port  }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "radarr"
