# This play book handles the downloading of necessary packages and applies firewall opening on the server.

- name: Verify EPEL is enabled
  yum: name={{item}} state=installed
  with_items:
    - epel-release

- name: Install necessary packages
  yum: name={{item}} state=installed
  with_items:
    - yum-utils
    - python-pip
    - docker-ce

- name: Install docker python module
  pip: name={{item}}
  with_items:
    - docker

- name: Start and Enable the docker service
  service:
    name: docker
    state: started
    enabled: yes

# Open up ports for all those dope applications.

- name: Open up the ports
  firewalld:
    port: "{{ item.portname }}/{{item.porttype}}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - { portname: "{{ plex_port }}", porttype: 'tcp'}
    - { portname: "{{ plex_port }}", porttype: 'udp'}
    - { portname: "{{ sab_port }}", porttype: 'tcp'}
    - { portname: "{{ sab_port }}", porttype: 'udp'}
    - { portname: "{{ radarr_port }}", porttype: 'tcp'}
    - { portname: "{{ radarr_port }}", porttype: 'udp'}
    - { portname: "{{ sonarr_port }}", porttype: 'tcp'}
    - { portname: "{{ sonarr_port }}", porttype: 'udp'}
    - { portname: "{{ hydra_port }}", porttype: 'tcp'}
    - { portname: "{{ hydra_port }}", porttype: 'udp'}
    - { portname: "{{ mylar_port }}", porttype: 'tcp'}
    - { portname: "{{ mylar_port }}", porttype: 'udp'}
    - { portname: "{{ lazyl_port }}", porttype: 'tcp'}
    - { portname: "{{ lazyl_port }}", porttype: 'udp'}
    - { portname: "{{ ubooquity_port }}", porttype: 'tcp'}
    - { portname: "{{ ubooquity_port }}", porttype: 'udp'}
    - { portname: "{{ ubooquity_admin_port }}", porttype: 'tcp'}
    - { portname: "{{ ubooquity_admin_port }}", porttype: 'udp'}
    - { portname: "{{ mtn_port }}", porttype: 'tcp'}
    - { portname: "{{ mtn_port }}", porttype: 'udp'}
