- name: setup and start the Sonarr container
  docker_container:
    image: "linuxserver/sonarr:latest"
    name: "sonarr"
    env:
      PUID: '{{ user_id }}'
      PGID: '{{ group_id }}'
    volumes:
      - '/dev/rtc:/dev/rtc:ro'
      - '{{ sonarr_directory }}:/config '
      - '{{ host_media_tv_path }}:/tv'
      - '{{ host_media_downloaded }}:/downloads'
    ports: '{{ sonarr_port }}:{{ sonarr_port }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "sonarr"
