- name: setup and start the NZBHydra container
  docker_container:
    image: "linuxserver/hydra:latest"
    name: "hydra"
    env:
      PUID: '{{ user_id }}'
      PGID: '{{ group_id }}'
      TZ: '{{ TZ_TimeZone  }}'
    volumes:
      - '{{ hydra_config }}:/config '
      - '{{ hydra_downloads_directory }}:/downloads'
    ports: "{{ hydra_port }}:{{ hydra_port }}"
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "hydra"
