# This play book handles the downloading of necessary packages and applies firewall opening on the server.

- name: Install necessary packages
  yum: name={{item}} state=installed
  with_items:
    - git
    - curl
    - wget
    - yum-utils
    - python-pip

- name: Add Docker Repo
  yum_repository:
    name: docker
    description: Docker Repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker Main
  yum:
    name: docker
    state: latest
  tags:
  - skip_ansible_lint

- name: Install docker-py
  pip: name={{item}}
  with_items:
    - docker
    - docker-py

- name: Start and Enable the docker service
  service:
    name: docker
    state: started
    enabled: yes

# Open up ports for all those dope applications.

- name: Open up the ports
  firewalld:
    port: "{{ item.portname }}/{{item.porttype}}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - { portname: "{{ plex_port }}", porttype: 'tcp'}
    - { portname: "{{ plex_port }}", porttype: 'udp'}
    - { portname: "{{ sab_port }}", porttype: 'tcp'}
    - { portname: "{{ sab_port }}", porttype: 'udp'}
    - { portname: "{{ radarr_port }}", porttype: 'tcp'}
    - { portname: "{{ radarr_port }}", porttype: 'udp'}
    - { portname: "{{ sonarr_port }}", porttype: 'tcp'}
    - { portname: "{{ sonarr_port }}", porttype: 'udp'}
    - { portname: "{{ hydra_port }}", porttype: 'tcp'}
    - { portname: "{{ hydra_port }}", porttype: 'udp'}
    - { portname: "{{ ombi_port }}", porttype: 'tcp'}
    - { portname: "{{ ombi_port }}", porttype: 'udp'}
    - { portname: "{{ organ_port }}", porttype: 'tcp'}
    - { portname: "{{ organ_port }}", porttype: 'udp'}
    - { portname: "{{ mylar_port }}", porttype: 'tcp'}
    - { portname: "{{ mylar_port }}", porttype: 'udp'}
    - { portname: "{{ lazyl_port }}", porttype: 'tcp'}
    - { portname: "{{ lazyl_port }}", porttype: 'udp'}
    - { portname: "{{ ubooq_port }}", porttype: 'tcp'}
    - { portname: "{{ ubooq_port }}", porttype: 'udp'}
